### ISSUE TITLE
GUI API in applications is broken after commit cadff0e8b09df8b3efd6bc0fb8a944c078d0ce85

### ISSUE THREAD

**Issue by d0iasm** [hikalium/wasabi#22]
GUI API in an application doesn't work well after https://github.com/hikalium/wasabi/commit/cadff0e8b09df8b3efd6bc0fb8a944c078d0ce85

Steps to reproduce:

1. $ git clone git@github.com:d0iasm/saba.git
2. $ cd saba
3. $ ./run_on_wasabi.sh

Result:
No cursor (red square) is shown.
https://github.com/user-attachments/assets/9fc39ba9-f1d7-4852-82e5-57425d8b4f31

Expected:
Cursor is displayed.
https://github.com/user-attachments/assets/b14c64ec-5e7b-43be-a0e9-b2392471af3d

**Comment by hikalium** [comment]
Sorry for the late reply... It should be fixed now! (it was not working because I implemented process scheduling but forgot to schedule OS process voluntarily on syscall executions so that there are no chances to handle key / mouse events in the OS side). Please re-open if the problem still persists. Thank you!

**Comment by hikalium** [comment]
FYI: I verified that the saba app displays mouse cursor correctly with the commit above (thanks for the awesome work!)
